### ISSUE TITLE
config GPIO with Pull-Up

### ISSUE THREAD

**Issue by Hagenmue** [mivallion/Encoder#2]
... so we need no external Pull-Up Resistors
`GPIO.setup(A, GPIO.IN, pull_up_down=GPIO.PUD_UP )
 GPIO.setup(B, GPIO.IN, pull_up_down=GPIO.PUD_UP)`

**Comment by mivallion** [comment]
Usually encoders contain resistors inside themselves, so I'm not sure about the need for pull-up resistors
